name: xesn
channels:
    - conda-forge
dependencies:
    - python=3.11
# Basics
    - numpy
    - scipy
      #- cupy
    - matplotlib
# xarray et al
    - xarray
    - netCDF4
    - bottleneck
    - dask[complete]
    - zarr
# ML and optim
    - smt
# jupyter etc
    - jupyter
# Testing
    - pytest
    - coverage
