xdata:
    dimensions            : ['x', 'time']
#
    zstore_path           : lorenz96-016d/trainer.zarr
    field_name            : 'trajectory'
    subsampling:
        time:
            training        : [ null, null, null]

    normalization:
        bias            : 0.
        scale           : 1.

lazyesn:
    boundary            : periodic
    n_reservoir         : 500
    leak_rate           : 0.5
    tikhonov_parameter  : 1.e-6
    persist             : True
#
    esn_chunks:
        x               : 2
        time            : -1
    overlap:
        x               : 1
        time            : 0
#
    input_kwargs:
        factor          : 1.0
        distribution    : uniform
        normalization   : svd
        is_sparse       : False
        random_seed     : 0
#
    adjacency_kwargs:
        factor          : 1.0
        format          : csr
        distribution    : uniform
        normalization   : svd
        is_sparse       : True
        connectedness   : 5
        random_seed     : 1
#
    bias_kwargs:
        factor          : 0.5
        distribution    : uniform
        random_seed     : 2

training:
    n_spinup            : 0
    batch_size          : null
