name: esn
channels:
    - conda-forge
dependencies:
    - python=3.10
# Basics
    - numpy
    - scipy
      #- cupy
    - matplotlib
# xarray et al
    - xarray
    - netCDF4
    - bottleneck
    - dask[complete]
    - zarr
# optional
    - seaborn
    - cmocean
# jupyter etc
    - jupyter
    - ipython
    - ipykernel
# Testing
    - pytest
    - coverage
# nice things
    - colordiff
# Specify blas to use mkl
    - mkl
    - libblas=*=*mkl
