# This uses actios:
#  checkout: https://github.com/actions/checkout
#  cache: https://github.com/actions/cache
#  codecov-action: https://github.com/codecov/codecov-action

name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          micromamba-version: "latest"
          environment-file: ci/environment.yaml
          create-args: python=${{ matrix.python-version }}
      - name: Install xesn
        shell: micromamba-shell {0}
        run: |
          python -V
          python -c "import setuptools; print(setuptools.__version__)"
          python -m pip install -e . --no-deps
      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          python -V
          coverage run --rcfile=coverage.toml -m pytest --verbose xesn/test/matrix.py xesn/test/esn.py xesn/test/lazy.py xesn/test/xdata.py xesn/test/optim.py xesn/test/psd.py xesn/test/cost.py xesn/test/driver.py
      - name: Get coverage report
        shell: bash -l {0}
        run: |
          coverage report -m ; coverage xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests # optional
