
name: Build Documentation
on:
  pull_request:
    branches:
      - "*"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('docs/environment.yaml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: xesn
          auto-update-conda: false
          python-version: 3.11
          environment-file: docs/environment.yaml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - name: Build Docs
        shell: bash -l {0}
        run: |
          cd docs ; make html
