
name: Build Documentation
on:
  pull_request:
    branches:
      - "*"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          cache-environment: true
          micromamba-version: "latest"
          environment-file: docs/environment.yaml
          create-args: python=${{ matrix.python-version }}
      - name: Install xesn
        shell: micromamba-shell {0}
        run: |
          python -V
          python -c "import setuptools; print(setuptools.__version__)"
          python -m pip install -e . --no-deps
      - name: Build Docs
        shell: bash -l {0}
        run: |
          cd docs ; make html
